name: PlotSquared-NekoAddon
main: com.github.SoyDary.PlotSquaredNekoAddon.PSNA
depend: [PlotSquared, PlaceholderAPI]
softdepend: [ProtocolLib, Essentials]
author: Dariela
version: 2.0.5
api-version: 1.13
commands:
 plotsquared-nekoaddon:
  description: Comando principal
  aliases: [psna, nekoplots]
 starboard:
  description: Menú de las mejores parcelas